{% set name = "databricks-cli" %}
{% set version = "0.17.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fea8b4e47ac38bd4eaad8a76e38a6916419df930ad1c615a6b43feb427672c4

build:
  number: 1
  entry_points:
    - databricks=databricks_cli.cli:cli
    - dbfs=databricks_cli.dbfs.cli:dbfs_group
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - click >=7.0
    - pyjwt >=1.7.0
    - oauthlib >=3.1.0
    - requests >=2.17.3
    - tabulate >=0.7.7
    - six >=1.10.0
    - configparser >=0.3.5  # [py<36]

test:
  requires:
    - pip
  imports:
    - databricks_cli
    - databricks_cli.cluster_policies
    - databricks_cli.clusters
    - databricks_cli.configure
    - databricks_cli.dbfs
    - databricks_cli.groups
    - databricks_cli.instance_pools
    - databricks_cli.jobs
    - databricks_cli.libraries
    - databricks_cli.oauth
    - databricks_cli.pipelines
    - databricks_cli.repos
    - databricks_cli.runs
    - databricks_cli.sdk
    - databricks_cli.secrets
    - databricks_cli.stack
    - databricks_cli.tokens
    - databricks_cli.unity_catalog
    - databricks_cli.workspace
  commands:
    - databricks --help
    - dbfs --help
    - pip check

about:
  home: https://github.com/databricks/databricks-cli
  summary: A command line interface for Databricks
  description: |
    The Databricks Command Line Interface (CLI) is an open source tool
    which provides an easy to use interface to the Databricks platform.
    The CLI is built on top of the Databricks REST APIs.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/databricks/databricks-cli
  doc_url: https://docs.databricks.com/dev-tools/cli/index.html

extra:
  recipe-maintainers:
    - thewchan
    - andrewmchen
    - jaroslawk
    - oblute