travis:
  secure:
    BINSTAR_TOKEN: LgCouEjFoVh29quKzK8w8ZnZMgABhE60aL5PeQoDrU/HiuWZPv7D8o3N1f7QHiLeRKlR1DinzIXOXIxXQ/zX57gOY6daMxfGRvCgnJkR3ADgG4Z8maXFLPtXFyUKJmwoBc9JDpBZnbhq96VrG/K3J+qncpjCJbLrw5FdlYxf4FSSWfAED1PzlRw1iSBJ3icqXsc7NnYhZK5ske77ter0suRwYsXbJQ5VX+kGkHVw9TcysUOlVRLO93ox5S9MJ1X6iEzn9jopqcyn2yTr1mvPtUvHSjERnIwFJER4cpg3WezoEftG9m06io+Ya66rQ/vPu/Hk9dlfq17iLhl9g8wN3AgK9N+bqFoMgX9cI1fBnVL4mSZ/HO59PW8z4Pxe4CvsB5qtb6PNMNwJt5YFqPIG9mRmsMrjAeunJKFYMrAe9p9NMIOs1hqVuHiyzJA9ecHd9aZPfRiVD7eK9cwrxW/zDrNykBOOO8rFky5LQp31FCddktwMlSog+oBzBr4I33bsoSoXH3oi8z4C3Yw8Q2IBrGV7IRXVE78Pl7AaBUlMMf6pQ+ZCGftF08ge4oXkQNH8Rki5J9vyhpcrAnFRmnvE7mpP+K0wiFQRgO04H2lP2+vpTsQa7Ae3HpgmDBrww2vdfhf9cZqMOciowzpmj7BIidh+lRE8v38QMWzRGoTNnQE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
